/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftS.IDL
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ThriftSRequest : TBase
  {
    private string _ServiceName;
    private string _MethodName;
    private List<ThriftSParameter> _Parameters;

    public Dictionary<string, string> Headers { get; set; }

    public string ServiceName
    {
      get
      {
        return _ServiceName;
      }
      set
      {
        __isset.ServiceName = true;
        this._ServiceName = value;
      }
    }

    public string MethodName
    {
      get
      {
        return _MethodName;
      }
      set
      {
        __isset.MethodName = true;
        this._MethodName = value;
      }
    }

    public List<ThriftSParameter> Parameters
    {
      get
      {
        return _Parameters;
      }
      set
      {
        __isset.Parameters = true;
        this._Parameters = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ServiceName;
      public bool MethodName;
      public bool Parameters;
    }

    public ThriftSRequest() {
    }

    public ThriftSRequest(Dictionary<string, string> Headers) : this() {
      this.Headers = Headers;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_Headers = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                Headers = new Dictionary<string, string>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  string _key2;
                  string _val3;
                  _key2 = iprot.ReadString();
                  _val3 = iprot.ReadString();
                  Headers[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
              isset_Headers = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              ServiceName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              MethodName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                Parameters = new List<ThriftSParameter>();
                TList _list4 = iprot.ReadListBegin();
                for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                {
                  ThriftSParameter _elem6;
                  _elem6 = new ThriftSParameter();
                  _elem6.Read(iprot);
                  Parameters.Add(_elem6);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_Headers)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ThriftSRequest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "Headers";
      field.Type = TType.Map;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteMapBegin(new TMap(TType.String, TType.String, Headers.Count));
        foreach (string _iter7 in Headers.Keys)
        {
          oprot.WriteString(_iter7);
          oprot.WriteString(Headers[_iter7]);
        }
        oprot.WriteMapEnd();
      }
      oprot.WriteFieldEnd();
      if (ServiceName != null && __isset.ServiceName) {
        field.Name = "ServiceName";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ServiceName);
        oprot.WriteFieldEnd();
      }
      if (MethodName != null && __isset.MethodName) {
        field.Name = "MethodName";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(MethodName);
        oprot.WriteFieldEnd();
      }
      if (Parameters != null && __isset.Parameters) {
        field.Name = "Parameters";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Parameters.Count));
          foreach (ThriftSParameter _iter8 in Parameters)
          {
            _iter8.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ThriftSRequest(");
      __sb.Append(", Headers: ");
      __sb.Append(Headers);
      if (ServiceName != null && __isset.ServiceName) {
        __sb.Append(", ServiceName: ");
        __sb.Append(ServiceName);
      }
      if (MethodName != null && __isset.MethodName) {
        __sb.Append(", MethodName: ");
        __sb.Append(MethodName);
      }
      if (Parameters != null && __isset.Parameters) {
        __sb.Append(", Parameters: ");
        __sb.Append(Parameters);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
