/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftS.IDL
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ThriftSResult : TBase
  {
    private byte[] _Data;

    public string ContentType { get; set; }

    /// <summary>
    /// 
    /// <seealso cref="ThriftS.IDL.ThriftSCompression"/>
    /// </summary>
    public ThriftS.IDL.ThriftSCompression Compression { get; set; }

    public byte[] Data
    {
      get
      {
        return _Data;
      }
      set
      {
        __isset.Data = true;
        this._Data = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Data;
    }

    public ThriftSResult() {
      this.Compression = ThriftS.IDL.ThriftSCompression.None;
    }

    public ThriftSResult(string ContentType, ThriftS.IDL.ThriftSCompression Compression) : this() {
      this.ContentType = ContentType;
      this.Compression = Compression;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_ContentType = false;
      bool isset_Compression = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              ContentType = iprot.ReadString();
              isset_ContentType = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Compression = (ThriftS.IDL.ThriftSCompression)iprot.ReadI32();
              isset_Compression = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Data = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_ContentType)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_Compression)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ThriftSResult");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "ContentType";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(ContentType);
      oprot.WriteFieldEnd();
      field.Name = "Compression";
      field.Type = TType.I32;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)Compression);
      oprot.WriteFieldEnd();
      if (Data != null && __isset.Data) {
        field.Name = "Data";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Data);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ThriftSResult(");
      __sb.Append(", ContentType: ");
      __sb.Append(ContentType);
      __sb.Append(", Compression: ");
      __sb.Append(Compression);
      if (Data != null && __isset.Data) {
        __sb.Append(", Data: ");
        __sb.Append(Data);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
